<?php


namespace mysticzap\tinetclink\tnet\v2\incomingcallrecord;


use mysticzap\tinetclink\tnet\v2\Api;

/**
 * 6.1.4. 同步呼入通话记录
 * @link [third api doc]https://develop.clink.cn/develop/api/cc.html#同步呼入通话记录
 * @package mysticzap\tinetclink\tnet\v2\incomingcallrecord
 */
class CopyCdrIbs extends Api
{
    /**
     * @var array 请求包含的参数，以及是否必填
     */
    public $requestParamsRequired = [
        // 是否隐藏号码。
        //0: 不隐藏，1: 中间四位，2: 最后八位，3: 全部号码，4: 最后四位。默认值为 0
        "hiddenType" => false,
        // 每次请求返回的参数，作为下次请求的必须参数。
        //for 循环第一次请求不需要传递此参数。 游标的存活时间为5分钟，当返回为noScrollId时您不应该再次使用此游标请求，因为它表示当前同步已结束。
        "scrollId" => true,
        // 指定同步某一天的通话记录。格式：yyyyMMdd, 例如：20180816
        "date" => true,
        // 查询条数，范围 10-100。默认值为 10
        "limit" => false,
    ];

    public $apiName = "同步呼入通话记录";
    public $api = '/cc/copy_cdr_ibs';
    public $method = self::METHOD_GET;

    /**
     * 接口调用返回数据
     * @param array $params
     * @param string $postParamType
     * @param array $headers
     * @return mixed
     * @example return {
     * "requestId":"ba078ace-717c-4dea-af41-d4dd5035edd6",
     * "scrollId":"DnF1ZXJ5VAWjB3AAAAAAAFl-8WSHUW0zV3GbG4wdw==",
     * "pageNumber":1,
     * "pageSize":10,
     * "totalCount":1,
     * "cdrIbs":[
     * {
     * "uniqueId":"AWS_DEV_MEDIA_SERVER_8-1537176819.4",
     * "hotline":"02788888888",
     * "customerNumber":"15388888888",
     * "customerNumberEncrypt":"TNjljZjZlNjgxYmIwNjMxZGEwMzA3MmQ0MDQzYWEyMjY",
     * "customerProvince":"北京",
     * "customerCity":"北京",
     * "qno":"0000",
     * "cno":"0010",
     * "clientName":"张三",
     * "clientNumber":"15388888888",
     * "callType":"呼入",
     * "startTime":15388888888,
     * "endTime":15388888888,
     * "bridgeTime":15388888888,
     * "bridgeDuration":3,
     * "totalDuration":33,
     * "ivrName":"mucw直呼队列",
     * "status":"座席接听",
     * "statusCode":"座席接听-1",
     * "endReason":"主通道挂机",
     * "sipCause":"",
     * "recordFile":null,
     * "userField":null,
     * "ivrFlows":[
     * {
     * "pathName":"-",
     * "path":"1",
     * "routerStartTime":15388888888,
     * "routerEndTime":15388888888,
     * "routerName":"非工作日路由",
     * "ivrName":"-",
     * "action":"播放",
     * "startTime":1537176821,
     * "endTime":1537176821
     * }
     * ],
     * "investigation":{
     * "startTime":15388888888,
     * "endTime":15388888888,
     * "cno":"2005",
     * "clientName":"客户端",
     * "keys":10
     * },
     * "tags":["标签1","标签2"],
     * "mark":2
     * }
     * ]
     * }
     */
    public function send($params, $postParamType = self::REQUEST_TYPE_FORM, $headers = [])
    {
        return parent::send($params, $postParamType, $headers); // TODO: Change the autogenerated stub
    }

}