<?php


namespace mysticzap\tinetclink\tnet\v2\outgoingcallrecord;


use mysticzap\tinetclink\tnet\v2\Api;

/**
 * 6.2.1. 查询外呼通话记录列表
 * @link [third api doc]https://develop.clink.cn/develop/api/cc.html#_查询外呼通话记录列表
 * @package mysticzap\tinetclink\tnet\v2\incomingcallrecord
 */
class ListCdrObs extends Api
{
    /**
     * @var array 请求包含的参数，以及是否必填
     */

    public $requestParamsRequired = [
        // 是否隐藏号码。
        //0: 不隐藏，1: 中间四位，2: 最后八位，3: 全部号码，4: 最后四位。默认值为 0
        "hiddenType" => false,
        // 队列号，要求只能是 4-6 位数字
        "qno" => false,
        // 客户号码
        "customerNumber" => false,
        // 座席号，要求只能是 4-11 位数字
        "cno" => false,
        // 热线号码
        "hotline" => false,
        // 接听状态。取值范围如下：
        //0: 全部
        //1: 座席接听
        //2: 已呼叫座席，座席未接听
        //3: 系统接听
        //4: 系统未接听-IVR配置错误
        //5: 系统未接听-停机
        //6: 系统未接听-欠费
        //7: 系统未接听-黑名单
        //8: 系统未接听-未注册
        //9: 系统未接听-彩铃
        //10: 系统未接听-网上400
        //11: 系统未接听-呼叫超出营帐中设置的最大限制
        //12: 系统未接听-客户呼入系统后在系统未应答前挂机
        //13: 其他错误
        // 默认值为0
        "status" => false,
        // 自定义字段
        "userField" => false,
        //标记。取值范围如下：
        //为空表示全部，
        //1:留言
        //2:转移
        //3:咨询
        //4:三方
        //5:传真接收
        //6:会议
        //7:交互
        //8:IVR中放弃
        //9:已进入IVR
        //10:未进入IVR
        //11:队列中放弃
        //12:队列中溢出
        //注： 其中mark值2,3,4,7仅在status=1(座席接听)时有效， mark值1,5,6,8,9,10,11,12在status=3(系统接听)时有效
        "mark" => false,
        // 客户省份
        "province" => false,
        // 客户城市
        "city" => false,
        // 通话记录唯一标识
        "mainUniqueId" => false,
        // 请求唯一标识
        "requestUniqueId" => false,
        // 座席电话
        "clientNumber" => false,
        //队列及时应答:
        //0: 否
        //1: 是
        //2: -
        "queueAnswerInTime" => false,
        //是否邀评:
        //0: 否
        //1: 是
        //2: -
        "evaluation" => false,
        // 开始时间，时间戳格式精确到秒。默认值取当前月份第一天
        "startTime" => false,
        //结束时间，时间戳格式精确到秒，开始时间和结束时间跨度不能超过一个月。默认值取当前时间
        "endTime" => false,
        // 偏移量，范围 0-99990。默认值为 0。注：limit + offset 不允许超过100000
        "offset" => false,
        // 查询条数，范围 10-100。默认值为 10。注：limit + offset 不允许超过100000
        "limit" => false,
    ];

    public $apiName = "查询外呼通话记录列表";
    public $api = '/cc/list_cdr_obs';
    public $method = self::METHOD_GET;

    /**
     * 接口调用返回数据
     * @param array $params
     * @param string $postParamType
     * @param array $headers
     * @return mixed
     * @example return {"requestId":"ba078ace-717c-4dea-af41-d4dd5035edd6","pageNumber":1,"pageSize":10,"totalCount":1,"cdrObs":[{"mainUniqueId":"AWS_DEV_MEDIA_SERVER_8-1536201058.19","hotline":"02788888888","customerNumber":"15388888888","customerNumberEncrypt":"TNjljZjZlNjgxYmIwNjMxZGEwMzA3MmQ0MDQzYWEyMjY","customerProvince":"北京","customerCity":"北京","cno":"","clientName":null,"clientNumber":null,"callType":"预览外呼","startTime":1536201058,"endTime":1536201060,"bridgeTime":null,"bridgeDuration":null,"totalDuration":2,"status":"系统接听","statusCode":"系统接听-3","endReason":"非主通道挂机","sipCause":"","recordFile":"","userField":{"c_cno":"2000","c_name":"2000test","c_exten":""},"mark":null,"tags":["标签1","标签2"],"queueAnswerInTime":0,"evaluation":0}]}
     */
    public function send($params, $postParamType = self::REQUEST_TYPE_FORM, $headers = [])
    {
        return parent::send($params, $postParamType, $headers); // TODO: Change the autogenerated stub
    }

}